// Command schemagen writes the Go description of a supported T3 Code schema
// from the fixtures in internal/store/testdata. Run it via go generate in
// internal/store.
package main

import (
	"bytes"
	"context"
	"flag"
	"fmt"
	"go/format"
	"log"
	"os"
	"strconv"

	"github.com/alcxyz/t3rry/internal/store"
)

func main() {
	version := flag.Int("version", 0, "highest migration id of the fixture to generate")
	flag.Parse()
	if *version <= 0 {
		log.Fatal("schemagen: -version is required")
	}

	schemaPath := fmt.Sprintf("testdata/schema-v%d.sql", *version)
	ledgerPath := fmt.Sprintf("testdata/migrations-v%d.txt", *version)
	schemaSQL, err := os.ReadFile(schemaPath)
	if err != nil {
		log.Fatalf("schemagen: %v", err)
	}
	ledger, err := os.ReadFile(ledgerPath)
	if err != nil {
		log.Fatalf("schemagen: %v", err)
	}
	schema, err := store.LoadFixture(context.Background(), string(schemaSQL), string(ledger))
	if err != nil {
		log.Fatalf("schemagen: %v", err)
	}
	if schema.MaxMigration != *version {
		log.Fatalf("schemagen: %s ends at migration %d, not %d", ledgerPath, schema.MaxMigration, *version)
	}

	var b bytes.Buffer
	fmt.Fprintf(&b, "// Code generated by schemagen from %s and %s; DO NOT EDIT.\n\n", schemaPath, ledgerPath)
	b.WriteString("package store\n\n")
	fmt.Fprintf(&b, "var schemaV%d = Schema{\n", *version)
	fmt.Fprintf(&b, "MaxMigration: %d,\n", schema.MaxMigration)
	b.WriteString("Migrations: []Migration{\n")
	for _, m := range schema.Migrations {
		fmt.Fprintf(&b, "{ID: %d, Name: %s},\n", m.ID, strconv.Quote(m.Name))
	}
	b.WriteString("},\n")
	b.WriteString("Tables: []Table{\n")
	for _, t := range schema.Tables {
		fmt.Fprintf(&b, "{\nName: %s,\nColumns: %s,\n", strconv.Quote(t.Name), stringSlice(t.Columns))
		if len(t.PrimaryKey) > 0 {
			fmt.Fprintf(&b, "PrimaryKey: %s,\n", stringSlice(t.PrimaryKey))
		}
		b.WriteString("},\n")
	}
	b.WriteString("},\n}\n")

	source, err := format.Source(b.Bytes())
	if err != nil {
		log.Fatalf("schemagen: format generated code: %v", err)
	}
	out := fmt.Sprintf("schema_v%d.go", *version)
	if err := os.WriteFile(out, source, 0o644); err != nil {
		log.Fatalf("schemagen: %v", err)
	}
}

func stringSlice(values []string) string {
	var b bytes.Buffer
	b.WriteString("[]string{")
	for i, v := range values {
		if i > 0 {
			b.WriteString(", ")
		}
		b.WriteString(strconv.Quote(v))
	}
	b.WriteString("}")
	return b.String()
}
